[browser]
gatherUsageStats = false
pageTitle = "Not Ready Time After Login Analysis"

[client]
showErrorDetails = false
toolbarMode = "minimal"
showSidebarNavigation = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
enableStaticServing = true

[global]
developmentMode = false

[ui]
hideTopBar = true
